billing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import signup_community, signup_org, signup_subscribe, signup_subscribe_session, subscription_success, subscription_cancel, manage_account, change_plan

import djstripe

app_name = 'billing'
urlpatterns = [
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path("signup/new/", signup_community, name="signup"),
    path("signup/<int:community_id>/", signup_org, name="signup_org"),
    path("signup/<int:community_id>/subscribe", signup_subscribe, name="signup_subscribe"),
    path("signup/<int:community_id>/session", signup_subscribe_session, name="signup_subscribe_session"),
    path("signup/<int:community_id>/success", subscription_success, name="subscription_success"),
    path("signup/<int:community_id>/cancel", subscription_cancel, name="subscription_cancel"),
    path("manage/<int:community_id>/", manage_account, name="manage_account"),
    path("upgrade/<int:community_id>/", change_plan, name="upgrade"),
]

demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import new_demo

app_name = 'demo'
urlpatterns = [
    #path('', include('savannah.urls')),
    path('new', new_demo, name='new'),
    #path('billing/', include('billing.urls')),
] 

savannah/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls

from corm.connectors import ConnectionManager

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/', include('apiv1.urls')),
    path('', include('frontendv2.urls')),

    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('billing/', include('billing.urls')),
    path('demo/', include('demo.urls')),
] 

for module, plugin in ConnectionManager.CONNECTOR_PLUGINS.items():
    plugin_name = module.rsplit(".", maxsplit=1)[-1]
    urlpatterns += path('%s/'%plugin_name, include(module)),

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except:
        # django-debug-toolbar is not installed
        pass

billing/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse
from django import forms
from django.db.models import Q

import json
import datetime
import operator

import stripe, djstripe
from djstripe import webhooks

from corm.models import Community
from billing.models import Organization, Management
from frontendv2.views import SavannahView, get_session_community
from corm.email import EmailMessage

from simple_ga import api as ga

# Create your views here.
class NewCommunityForm(forms.ModelForm):
    class Meta:
        model = Community
        fields = ['name', 'logo']
    
class CommunityCreationEmail(EmailMessage):
    def __init__(self, community):
        super(CommunityCreationEmail, self).__init__(community.owner, community)
        self.subject = "A new community had been created: %s" % self.community.name
        self.category = "community_creation"

        self.text_body = "emails/new_community_created.txt"
        self.html_body = "emails/new_community_created.html"


@login_required
def signup_community(request):
    community = Community(owner=request.user)
    if request.method == "POST":
        form = NewCommunityForm(request.POST, files=request.FILES, instance=community)
        if form.is_valid():
            new_community = form.save()
            new_community.bootstrap()
            msg = CommunityCreationEmail(new_community)
            msg.send(settings.ADMINS)
            # Redirect to company creation form
            #messages.success(request, "Welcome to your new Communtiy! Learn what to do next in our <a target=\"_blank\" href=\"http://docs.savannahhq.com/getting-started/\">Getting Started</a> guide.")
            ga.add_event(request, 'community_creation', category='signup')
            return redirect('billing:signup_org', community_id=new_community.id)
    else:
        form = NewCommunityForm(instance=community)

    context = {
        "form": form,
    }
    return render(request, 'billing/signup_community.html', context)


@login_required
def signup_org(request, community_id):
    # If community doesn't exist
        # Redirect to community signup form
    try:
         community = Community.objects.get(Q(owner=request.user) | Q(managers__in=request.user.groups.all()), id=community_id)
    except Exception as e:
        messages.error(request, "Unknown Community")
        return redirect('billing:signup')

    stripe.api_key =settings.STRIPE_SECRET_KEY
    # If community has a company
        # Redirect to subscription form
    try:
        management = Management.objects.get(community=community)
        return redirect('billing:signup_subscribe', community_id=community.id)
    except:
        pass

    try:
        customer = stripe.Customer.create(
            email=request.user.email,
            name=community.name,
        )
        djstripe_customer = djstripe.models.Customer.sync_from_stripe_data(customer)
        djstripe_customer.subscriber = community
        djstripe_customer.save()
        org, created = Organization.objects.get_or_create(customer=djstripe_customer, defaults={'name': community.name, 'email': request.user.email})

        management, created = Management.objects.get_or_create(org=org, community=community)
        ga.add_event(request, 'org_creation', category='signup')
        return redirect('sources', community_id=community.id)
    except Exception as e:
        messages.error(request, "Failed to find or create a billing organization for %s" % community.name)
        messages.error(request, e)
        customer = None
        org = None
        return redirect('billing:signup')

@login_required
def signup_subscribe_session(request, community_id,):
 
    management = get_object_or_404(Management, community_id=community_id)
    community = management.community
    org = management.org
    plan_id = request.GET.get('plan', None)
    plan = get_object_or_404(djstripe.models.Plan, id=plan_id)
    line_items = [
                {
                    "price": plan_id,
                    "quantity": 1
                }
            ]
    if plan.billing_scheme == 'tiered':
        line_items = [
                {
                    "price": plan_id,
                    "quantity": management.billable_seats
                }
            ]
    if request.method == 'POST':
 
        # Set Stripe API key
        stripe.api_key = settings.STRIPE_SECRET_KEY
 
        # Create Stripe Checkout session
        checkout_session = stripe.checkout.Session.create(
            # payment_method_types=["card"], # New Stripe checkout allows other options if this is omitted
            mode="subscription",
            client_reference_id=community.id,
            allow_promotion_codes=True,
            line_items=line_items,
            customer=org.customer.id,
            success_url=settings.SITE_ROOT + reverse('billing:subscription_success', kwargs={'community_id': community.id}) + "?session_id={CHECKOUT_SESSION_ID}",
            cancel_url= settings.SITE_ROOT + reverse('billing:subscription_cancel', kwargs={'community_id': community.id}), # The cancel_url is typically set to the original product page
        )

    return JsonResponse({'sessionId': checkout_session['id']})

@login_required
def signup_subscribe(request, community_id):
    # If community has a subscription
        # Redirect to Stripe customer portal

    management = get_object_or_404(Management, community_id=community_id)
    community = management.community
    org = management.org

    savannah_crm = djstripe.models.Product.objects.get(id=settings.STRIPE_PRODUCT_ID)
    plans = djstripe.models.Plan.objects.filter(product=savannah_crm, active=True).order_by('created', 'amount')
    costs = dict()
    for plan in plans:
        if plan.billing_scheme == 'tiered':
            cost = 0
            for tier in plan.tiers:
                if tier['flat_amount']:
                    cost += tier['flat_amount']
                    plan.has_flat_amount = True
                if tier['unit_amount']:
                    cost += tier['unit_amount']
                    plan.has_unit_amount = True
            costs[plan] = cost / 100
        else:
            costs[plan] = plan.amount

    context = {
        "community": community,
        "org": org,
        "plans": [p for p, c in sorted(costs.items(), key=operator.itemgetter(1), reverse=False)],
        "STRIPE_KEY": settings.STRIPE_PUBLIC_KEY,
    }
    ga.add_event(request, 'subcription_options_viewed', category='signup')
    return render(request, 'billing/signup_subscribe.html', context)


@login_required
def create_checkout_session(request, community_id):
    # Create Stripe.checkout.Session
        # Use community_id as client_reference_id
    # Return session id in JSON
    pass

@login_required
def subscription_success(request, community_id):
    # Redirect to Community dashboard
    community = get_object_or_404(Community, id=community_id)
    messages.success(request, "Your subscription to Savannah CRM has begun!")
    ga.add_event(request, 'subcription_created', category='signup')
    return redirect('dashboard', community_id=community.id)

@login_required
def subscription_cancel(request, community_id):
    # Redirect to subscribe_community
    community = get_object_or_404(Community, id=community_id)
    messages.error(request, "Unable to process your subscription")
    ga.add_event(request, 'subcription_abort', category='signup')
    return redirect('billing:signup_subscribe', community_id=community.id)

@webhooks.handler("checkout.session.completed")
def checkout_session_completed(event, **kwargs):
    # Get community_id from client_reference_id
    session = event.data["object"]
    community_id = session["client_reference_id"]
    subscription_id = session["subscription"]
    management = Management.objects.get(community_id=community_id)

    # Add subscription to Management model of this community
    management.subscribe(subscription_id)

@webhooks.handler("customer.subscription.deleted")
def subscription_canceled(event, **kwargs):
    # Deactive the community this subscription belonged to
    subscription = event.data["object"]
    Management.unsubscribe(subscription['id'])

class TrialEndingEmail(EmailMessage):
    def __init__(self, community):
        system_user = get_object_or_404(User, username=settings.SYSTEM_USER)
        super(TrialEndingEmail, self).__init__(system_user, community)
        self.subject = "Your trial period for %s is about to end" % self.community.name
        self.category = "trial_ending"

        self.text_body = "emails/trial_ending.txt"
        self.html_body = "emails/trial_ending.html"

@webhooks.handler("customer.subscription.trial_will_end")
def send_trial_end_email(event, **kwargs):
    subscription = event.data["object"]
    mgmt = Management.objects.get(subscription__id=subscription['id'])
    community = mgmt.community
    msg = TrialEndingEmail(community)
    msg.context.update({
        "trial_end": datetime.datetime.fromtimestamp(subscription["trial_end"]),
        "price":   (subscription["plan"]["amount"]/100),
        "currency": subscription["plan"]["currency"],
        "interval": subscription["plan"]["interval"],
    })
    msg.send(community.owner.email)

class PaymentFailedEmail(EmailMessage):
    def __init__(self, community):
        system_user = get_object_or_404(User, username=settings.SYSTEM_USER)
        super(PaymentFailedEmail, self).__init__(system_user, community)
        self.subject = "Problems with your Savannah CRM account"
        self.category = "billing_error"

        self.text_body = "emails/payment_failed.txt"
        self.html_body = "emails/payment_failed.html"

@webhooks.handler("invoice.payment_failed")
def payment_failed(event, **kwargs):

billing/templates/billing/change_plan.html
{% extends "savannahv2/blank.html" %}
{% load humanize static simple_math %}


{% block page_title %} | Select your plan{% endblock %}

{% block page_content %}

<!-- Content Row -->
<div class="row mt-5 justify-content-center">
<div class="col-12 mb-5 mt-8 align-items-center">
<center>
    <div class="card shadow h-100 py-2">
    <div class="card-body">
        <div class="align-items-center">
            <h2>Change your plan:</h2>
            <div class="row justify-content-center">
              {% for plan in plans %}
              <div class="card shadow h-100 p-0 py-0 col border border-primary m-3">
                <div class="card-body">
                  <h5 class="card-title">{{plan.nickname}}</h5>
                    {% if plan.billing_scheme == 'tiered' %}
                      {% for tier in plan.tiers %}
                        {% comment %} {{tier}} {% endcomment %}
                        {% if tier.flat_amount %}
                        <div class="mb-1 font-weight-bold text-gray-800">${{tier.flat_amount|cents|floatformat:2}} /{{plan.interval}} for {{tier.up_to}} Managers</div>
                        {% endif %}
                        {% if tier.unit_amount %}
                          {% if plan.has_flat_amount %}
                            <div class="mb-1 font-weight-bold text-gray-800">+ ${{tier.unit_amount|cents|floatformat:2}} /{{plan.interval}} for each additional</div>
                          {% else %}
                          <div class="mb-1 font-weight-bold text-gray-800">${{tier.unit_amount|cents|floatformat:2}} /{{plan.interval}} per Manager</div>
                          {% endif %}
                        {% endif %}
                      {% endfor %}
                    {% else %}
                    <div class="mb-1 font-weight-bold text-gray-800">${{plan.amount|as_int}} /{{plan.interval}}</div>
                    <div class="mb-1 font-weight-bold text-gray-800">Unlimited Managers</div>
                    {% endif %}
                  <div class="card-text">
                    <div class="p-2 justify-content-left">
                        <div class="text-left">
                          <i class="fas fa-check-square text-primary"> </i> Unlimited Members
                        </div>
                        <div class="text-left">
                            <i class="fas fa-check-square {% if plan.metadata.managers|as_int == 0 %}text-primary{% else %}text-secondary{% endif %}"> </i> 
                            {{plan.metadata.managers|default:'Unlimited'}} Manager{% if plan.metadata.managers|as_int != 1 %}s{% endif %}
                        </div>
                        <div class="text-left">
                            <i class="fas fa-check-square {% if plan.metadata.sources|as_int == 0 %}text-primary{% else %}text-secondary{% endif %}"> </i> 
                            {{plan.metadata.sources|default:'Unlimited'}} Data Source{% if plan.metadata.sources|as_int != 1 %}s{% endif %}
                        </div>
                        <div class="text-left">
                            <i class="fas fa-check-square {% if plan.metadata.projects|as_int == 0 %}text-primary{% else %}text-secondary{% endif %}"> </i> 
                            {{plan.metadata.projects|default:'Unlimited'}} Project{% if plan.metadata.projects|as_int != 1 %}s{% endif %}
                        </div>
                        <div class="text-left">
                            <i class="fas fa-check-square {% if plan.metadata.tags|as_int == 0 %}text-primary{% else %}text-secondary{% endif %}"> </i> 
                            {{plan.metadata.tags|default:'Unlimited'}} Tag{% if plan.metadata.tags|as_int != 1 %}s{% endif %}
                        </div>
                        <div class="text-left">
                            <i class="{% if plan.metadata.sales_integration == "true" %}fas fa-check-square text-primary{% else %}far fa-square text-secondary{% endif %}"> </i> 
                            {% if plan.metadata.sales_integration == "true" %}Salesforce integration{% else %}No sales integrations{% endif %}
                        </div>

                    </div>
                    {% if plan.id == current_plan.id %}
                    <a class="btn btn-primary" href="{% url 'billing:manage_account' community.id %}">Change Billing Info</a>
                    {% else %}
                    <form class="inline-form" action="{% url 'billing:upgrade' community.id %}" method="POST">
                      {% csrf_token%}
                      <input type="hidden" name="plan_id" value="{{plan.id}}"/>
                      <button class="btn btn-success" type="submit">Switch to Plan</button>
                    </form>
                    {% endif %}
                    </div>
                  </div>
              </div>
              {% endfor %}
            </div>

            <div class="text-muted text-small mt-2">
            Savannah uses Stripe for payment processing
                    <div class="mb-1 small text-gray-500">Cancel any time.</div>
                  </div>

            <div>
            <br/> 
            <a class="btn btn-sm btn-secondary" href="{% url 'managers' community.id %}"><i class="fas fa-chevron-left"> </i> Back</a>
            <a class="btn btn-sm btn-danger" href="{% url 'billing:manage_account' community.id %}">Cancel Plan</a>

            </div>
        </div>
    </div>
    </div>
</center>
</div>
</div>
<!-- End row -->

{% endblock %}

billing/templates/billing/signup_community.html
{% extends "savannahv2/blank.html" %}
{% load humanize static %}
{% load crispy_forms_tags %}

{% block page_title %} | Start your Community{% endblock %}

{% block page_content %}


<!-- Content Row -->
<div class="row mt-5 justify-content-center">
<div class="col-xl-68 col-md-8 mb-5 mt-8 align-items-center">
<center>
    <div class="card shadow h-100 py-2">
    <div class="card-body">
        <div class="align-items-center">
            <h2>Get Started with Savannah</h2>

            <form class="form" action="{% url 'billing:signup' %}" method="POST" enctype="multipart/form-data">
            <div class="row justify-content-center">
            <div class="text-left col-8 mb-3">
            {% csrf_token %}
            {{form|crispy}}
            </div>
            </div>
            <button class="btn btn-success" type="submit">Add Your Community</button>
            </form>
        </div>
    </div>
    </div>
</center>
</div>
</div>
<!-- End row -->

{% endblock %}

billing/templates/billing/signup_org.html
{% extends "savannahv2/blank.html" %}
{% load humanize static %}
{% load crispy_forms_tags %}

{% block page_title %} | Start your Community{% endblock %}

{% block page_content %}


<!-- Content Row -->
<div class="row mt-5 justify-content-center">
<div class="col-xl-6 col-md-6 mb-8 mt-8 align-items-center">
<center>
    <div class="card shadow h-100 py-2">
    <div class="card-body">
        <div class="align-items-center">
            <h2>Get Started with Savannah</h2>

            <form class="form" action="{% url 'add-community' %}" method="POST" enctype="multipart/form-data">
            <div class="row justify-content-center">
            <div class="text-left col-8 mb-3">
            {% csrf_token %}
            {{form|crispy}}
            </div>
            </div>
            <button class="btn btn-success" type="submit">Step 1: Add Your Community</button>
            </form>
        </div>
    </div>
    </div>
</center>
</div>
</div>
<!-- End row -->

{% endblock %}

billing/templates/billing/signup_subscribe.html
{% extends "savannahv2/blank.html" %}
{% load humanize static simple_math %}


{% block page_title %} | Start your Community{% endblock %}

{% block page_styles %}
  <script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block page_content %}

<!-- Content Row -->
<div class="row mt-5 justify-content-center">
<div class="col-12 mb-5 mt-8 align-items-center">
<center>
    <div class="card shadow h-100 py-2">
    <div class="card-body">
        <div class="align-items-center">
            <h2>Pick your plan:</h2>
            <div class="row justify-content-center">
              {% for plan in plans %}
              <div class="card shadow h-100 p-0 py-0 col border border-primary m-3">
                <div class="card-body">
                  <h5 class="card-title">{{plan.nickname}}</h5>
                  {% if plan.billing_scheme == 'tiered' %}
                  {% for tier in plan.tiers %}
                    {% comment %} {{tier}} {% endcomment %}
                    {% if tier.flat_amount %}
                    <div class="mb-1 font-weight-bold text-gray-800">${{tier.flat_amount|cents|floatformat:2}} /{{plan.interval}} for {{tier.up_to}} Managers</div>
                    {% endif %}
                    {% if tier.unit_amount %}
                      {% if plan.has_flat_amount %}
                        <div class="mb-1 font-weight-bold text-gray-800">+ ${{tier.unit_amount|cents|floatformat:2}} /{{plan.interval}} for each additional</div>
                      {% else %}
                      <div class="mb-1 font-weight-bold text-gray-800">${{tier.unit_amount|cents|floatformat:2}} /{{plan.interval}} per Manager</div>
                      {% endif %}
                    {% endif %}
                  {% endfor %}
                {% else %}
                <div class="mb-1 font-weight-bold text-gray-800">${{plan.amount|as_int}} /{{plan.interval}}</div>
                <div class="mb-1 font-weight-bold text-gray-800">Unlimited Managers</div>
                {% endif %}
              <div class="card-text">
                    <div class="p-2 justify-content-left">
                        <div class="text-left">
                          <i class="fas fa-check-square text-primary"> </i> Unlimited Members
                        </div>
                        <div class="text-left">
                          <i class="fas fa-check-square {% if plan.metadata.managers|as_int == 0 %}text-primary{% else %}text-secondary{% endif %}"> </i> 
                          {{plan.metadata.managers|default:'Unlimited'}} Manager{% if plan.metadata.managers|as_int != 1 %}s{% endif %}
                      </div>
                      <div class="text-left">
                            <i class="fas fa-check-square {% if plan.metadata.sources|as_int == 0 %}text-primary{% else %}text-secondary{% endif %}"> </i> 
                            {{plan.metadata.sources|default:'Unlimited'}} Data Source{% if plan.metadata.sources|as_int != 1 %}s{% endif %}
                        </div>
                        <div class="text-left">
                            <i class="fas fa-check-square {% if plan.metadata.projects|as_int == 0 %}text-primary{% else %}text-secondary{% endif %}"> </i> 
                            {{plan.metadata.projects|default:'Unlimited'}} Project{% if plan.metadata.projects|as_int != 1 %}s{% endif %}
                        </div>
                        <div class="text-left">
                            <i class="fas fa-check-square {% if plan.metadata.tags|as_int == 0 %}text-primary{% else %}text-secondary{% endif %}"> </i> 
                            {{plan.metadata.tags|default:'Unlimited'}} Tag{% if plan.metadata.tags|as_int != 1 %}s{% endif %}
                        </div>
                        <div class="text-left">
                            <i class="{% if plan.metadata.sales_integration == "true" %}fas fa-check-square text-primary{% else %}far fa-square text-secondary{% endif %}"> </i> 
                            {% if plan.metadata.sales_integration == "true" %}Salesforce integration{% else %}No sales integrations{% endif %}
                        </div>

                    </div>
                    <button onClick="subscribeClicked('{{plan.id}}');" class="btn {% if forloop.first or forloop.last %}btn-primary{% else %}btn-success{% endif %}" type="submit">{{plan.nickname}}</button>
                    </div>
                  </div>
              </div>
              {% endfor %}
            </div>

            <div class="text-muted text-small mt-2">
            Savannah uses Stripe for payment processing
                    <div class="mb-1 small text-gray-500">Cancel any time.</div>
            </div>

            <div>
            <br/>
            <a class="btn btn-sm btn-secondary" href="{% url 'dashboard' community.id %}"><i class="fas fa-chevron-left"> </i> Back</a>
            <a class="btn btn-sm btn-secondary" href="https://savannahhq.com/request-a-demo">Request a Demo</a>
            </div>
        </div>
    </div>
    </div>
</center>
</div>
</div>
<!-- End row -->

{% endblock %}

{% block page_scripts %}
<script>
     var DOMAIN = window.location.origin;
 
      var stripe = Stripe("{{ STRIPE_KEY }}");
 
      // Handle any errors from Checkout
      var handleResult = function (result) {
        if (result.error) {
          var displayError = document.getElementById("error-message");
          displayError.textContent = result.error.message;
        }
      };
 
      // Create a Checkout Session with the selected plan ID
      var createCheckoutSession = function(plan_id) {
        return fetch("{% url 'billing:signup_subscribe_session' community.id %}?plan="+plan_id, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken":  '{{csrf_token}}',
          },
          // ... body section if you want to pass the product or price_id to the backend
        }).then(function(result) {
          return result.json();
        });
      };
 
    // Setup event handler to create a Checkout Session when button is clicked
    var subscribeClicked = function(plan_id) {
          createCheckoutSession(plan_id).then(function(data) {
            // Call Stripe.js method to redirect to the new Checkout page
            stripe
              .redirectToCheckout(
                {
                    sessionId: data.sessionId
                }
              )
              .then(handleResult);
          });
        };
</script>
{% endblock %}